name: "build examples"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_BROKEN=1
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: cd examples && nix-build
