name: "build examples"
on:
  pull_request:
  push:
jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples:
          - revealjs
          - simple
          - srcAsResourceDir
          - toHtml
          - withAdditionalPackges
          - withBibliography
          - withCodeBlocks
          - withCsl
          - withImage
          - withLatexTemplate
          - withVariables
    env:
      NIXPKGS_ALLOW_BROKEN: 1
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build examples/${{ matrix.examples }}.nix
