name: "build examples nixos-unstable"
on:
  pull_request:
  push:
jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - revealjs
          - simple
          - srcAsResourceDir
          - toHtml
          - withAdditionalPackges
          - withCodeBlocks
          - withImage
          - withVariables
          - withLatexTemplate
          # pandoc-citeproc is currently broken in nixos-unstable
          # - withCsl
          # - withBibliography
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build examples/${{ matrix.example }}.nix
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.example }}-result
        path: result
        retention-days: 1